site_name: 空山虚雨
theme: 
  name: material
  icon:
    logo: material/library
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式

  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - search.suggest
    - search.highlight
    - search.suggest   # 搜索输入一些字母时推荐补全整个单词
    - search.highlight   # 搜索出的文章关键词加入高亮
    - search.share   #搜索分享按钮
  language: zh

nav:
  - 附录: 
    - 生活记录: 生活/生活.md
    - 中华文化:
      - 庄子: 中华文化/庄子/庄子.md
  - 主页: index.md
  - 计算机:
    - C语言: 计算机/C语言/文件.md
    - Linux: 计算机/Linux/文件1.md
    - 计算机组成: 计算机/计算机组成/文件.md
plugins:
  - search
  - mermaid2:
      arguments:
        theme: light

extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
extra:
  homepage: http://kongshanxuyu.github.io/zh-blog
  social: # icons
#   - icon: fontawesome/brands/bilibili
#     link: https://space.bilibili.com/1436476753
#     name: Bilibili | 浩哈哈哈哈 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/KongshanXuyu
      name: GitHub | KongshangXuyu
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/2120194476?spm_id_from=333.1007.0.0
      name: bilibili | 空山虚雨
## [bottom-left corner]
copyright: Copyright &copy; 2023-现在 空山虚雨 # 左下角的版权声明
